site_name: "Rzk tutorials for the HoTT Seminar at BMSTU, November 20–21, 2023"
repo_url: https://github.com/fizruk/bmstu-rzk-demo-2023
repo_name: fizruk/bmstu-rzk-demo-2023
edit_uri: edit/main

docs_dir: src
nav:
  - About: index.md
  - Setup and Rzk overview: 1-setup.rzk.md
  - Day 1:
    - Dependent types: day-1/1-dependent-types.rzk.md
    - Propositions as types: day-1/2-propositions-as-types.rzk.md
    - Identity types: day-1/3-identity-types.rzk.md
    - Homotopy type theory: day-1/4-homotopy-type-theory.rzk.md
    - Exercises: day-1/5-exercises.rzk.md
  - Day 2:
    - Univalence: day-2/1-univalence.rzk.md
    - Sets and Logic in HoTT: day-2/2-sets-and-logic.rzk.md
    - Exercises: day-2/3-exercises.rzk.md
    - Simplicial HoTT: day-2/4-simplicial-types.rzk.md

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - mdx_math
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo-1000x1000.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - content.code.copy
    - content.action.edit
    - navigation.footer
    - navigation.sections
    - navigation.path
    - toc.integrate
  font:
    code: Fira Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/css/rzk-render.css

plugins:
  - search
  - rzk:
      render_svg: false # multi-file projects are not supported well
      anchor_definitions: true
